# Generated by Django 3.0.3 on 2020-07-25 03:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regTests',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=['t0', 't1'], max_length=110, size=10),
            preserve_default=False,
        ),
    ]
