# Generated by Django 3.0.3 on 2020-07-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_regtests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='u0', max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
