# Generated by Django 3.0.3 on 2020-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200727_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='t0', max_length=10),
            preserve_default=False,
        ),
    ]
