# Generated by Django 3.0.3 on 2020-07-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
