# Generated by Django 3.0.3 on 2020-07-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=400)),
            ],
        ),
    ]
