# Generated by Django 3.0.3 on 2020-07-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200725_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
