# Generated by Django 3.0.3 on 2020-07-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200725_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='content',
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('qid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='SAQuestion',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('qid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('qid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('A', models.CharField(max_length=100)),
                ('B', models.CharField(max_length=100)),
                ('C', models.CharField(max_length=100)),
                ('D', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
    ]
