# Generated by Django 3.0.3 on 2020-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20200727_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='test',
            field=models.ManyToManyField(to='tests.Test'),
        ),
        migrations.RemoveField(
            model_name='saquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='saquestion',
            name='test',
            field=models.ManyToManyField(to='tests.Test'),
        ),
        migrations.RemoveField(
            model_name='tfquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='tfquestion',
            name='test',
            field=models.ManyToManyField(to='tests.Test'),
        ),
    ]
