# Generated by Django 3.0.3 on 2020-07-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200727_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCQuestion',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='tfquestion',
            name='test',
        ),
        migrations.DeleteModel(
            name='SAQuestion',
        ),
        migrations.DeleteModel(
            name='TFQuestion',
        ),
    ]
